Add debuild and rpmbuild commands

diff --git a/pex b/pex
--- a/pex
+++ b/pex
@@ -7,6 +7,7 @@ Usage:
   pex audit [PACKAGE]...
   pex cat PACKAGE...
   pex create -n NAME URL
+  pex debuild PACKAGE
   pex edit [PACKAGE]...
   pex fetch PACKAGE...
   pex home [PACKAGE]...
@@ -16,6 +17,7 @@ Usage:
   pex ls|list
   pex outdated
   pex repotest
+  pex rpmbuild PACKAGE
   pex search [SUBSTRING]
   pex update [--rebase]
   pex upgrade [PACKAGE]...
@@ -168,6 +170,76 @@ EOF
 }
 
 
+cmd_debuild() {
+	local homepage pgmajorversion pgversion pkg
+
+	pkg=$1
+	shift
+
+	pgversion=$("$pg_config" --version)
+	pgmajorversion=$(expr "$pgversion" : '^.* \([0-9][0-9]*\.[0-9][0-9]*\)')
+
+	package_file=$(_package_file "$pkg")
+	homepage=$(parse_yaml_field "$package_file" homepage)
+	package_version=$(_package_version "$pkg")
+
+	target=$(_fetch_one "$pkg")
+
+	rm -rf "$work_dir/$pkg/debuild"
+	mkdir -p "$work_dir/$pkg/debuild"
+
+	(
+		cd "$work_dir/$pkg/debuild"
+		output "Unpacking $pkg"
+		unpack "$target"
+		ln -s $target ${pkg}_${package_version}.orig.tar.gz  # FIXME
+		cd "$pkg"*  # FIXME
+		rm -rf debian/
+		mkdir debian
+		echo 9 >debian/compat
+		mkdir debian/source
+		case $target in
+			*.zip) echo '3.0 (native)' >debian/source/format;;
+			*) echo '3.0 (quilt)' >debian/source/format;;
+		esac
+		: ${DEBFULLNAME=${NAME=$(getent passwd $(whoami) | cut -d : -f 5)}}
+		: ${DEBEMAIL=${EMAIL=$(whoami)@$(hostname --fqdn)}}
+		cat <<EOF >debian/control
+Source: $pkg
+Section: database
+Priority: extra
+Maintainer: $DEBFULLNAME <$DEBEMAIL>
+Build-Depends: debhelper (>= 9), postgresql-server-dev-$pgmajorversion
+Standards-Version: 3.9.3
+Homepage: $homepage
+
+Package: postgresql-$pgmajorversion-$pkg
+Architecture: any
+Depends: postgresql-$pgmajorversion, \${misc:Depends}, \${shlibs:Depends}
+Description: $pkg
+ This package of $pkg was automatically generated by pex.
+EOF
+		dch --create --package="$pkg" --newversion="${package_version}-1pex" 'Automatic changelog entry'
+		dch -r -D pex --force-distribution ''
+		cat <<EOF >debian/rules
+#!/usr/bin/make -f
+
+export PG_CONFIG = $pg_config
+export USE_PGXS = 1
+
+%:
+	dh \$@
+
+override_dh_auto_test: ;
+EOF
+		chmod a+x debian/rules
+		output "Building Debian package $pkg"
+		debuild "$@"
+	) || exit
+	output "Build results are in $work_dir/$pkg/debuild/"
+}
+
+
 cmd_fetch() {
 	local pkg
 
@@ -307,6 +379,68 @@ cmd_repotest() {
 }
 
 
+cmd_rpmbuild() {
+	local homepage package_file package_version pkg
+
+	pkg=$1
+	shift
+
+	pgrpmname=$(rpm -q -f "$pg_config" --queryformat '%{NAME}')
+	test -n "$pgrpmname"
+
+	package_file=$(_package_file "$pkg")
+	homepage=$(parse_yaml_field "$package_file" homepage)
+        package_version=$(_package_version "$pkg")
+
+	target=$(_fetch_one "$pkg")
+	target_basename=$(basename $target)
+
+	rm -rf "$work_dir/$pkg/rpmbuild"
+        mkdir -p "$work_dir/$pkg/rpmbuild"
+
+	cat <<EOF >$work_dir/$pkg/rpmbuild/$pkg.spec
+Name:           $pgrpmname-$pkg
+Version:        $package_version
+Release:        1%{?dist}
+Summary:        $pkg
+Group:          Databases
+License:        unknown
+URL:            $homepage
+Source:         $target_basename
+
+BuildRequires:  $pgrpmname
+
+BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
+
+%description
+This package of $pkg was automatically generated by pex.
+
+%prep
+%setup -q -n $pkg-%{version}
+
+%build
+make %{?_smp_mflags} USE_PGXS=1 PG_CONFIG=$pg_config
+
+%install
+make %{?_smp_mflags} USE_PGXS=1 PG_CONFIG=$pg_config install DESTDIR=\$RPM_BUILD_ROOT
+
+%clean
+rm -rf \$RPM_BUILD_ROOT
+
+%files
+%defattr(-,root,root,-)
+/
+EOF
+
+	rpm_sourcedir=$(rpmbuild -E '%_sourcedir' "$work_dir/$pkg/rpmbuild/$pkg.spec" 2>/dev/null || :)
+	mkdir -p "$rpm_sourcedir"
+	ln -sf "$target" "$rpm_sourcedir"
+
+	output "Building RPM package $pkg"
+	rpmbuild "$work_dir/$pkg/rpmbuild/$pkg.spec" "$@"
+}
+
+
 cmd_search() {
 	if [ $# -gt 1 ]; then
 		error '"search" takes zero or one arguments'
@@ -416,6 +550,30 @@ _package_file() {
 		error "package \"$pkg\" does not exist"
 	fi
 	echo "$filename"
+}
+
+
+_package_version() {
+	local pkg package_file
+
+	pkg=$1
+	package_file=$(_package_file "$pkg")
+	url=$(parse_yaml_field "$package_file" url)
+	base=$(basename "$url")
+	without_ext=$(echo "$base" | sed 's/\.[^.]*$//;s/\.tar//')
+
+	case $without_ext in
+		*-*)
+			version=$(echo "$without_ext" | sed 's/^.*-//');;
+		*_*)
+			version=$(echo "$without_ext" | sed 's/^.*_//');;
+		[0-9]*)
+			version=$without_ext;;
+		*)
+			error "cannot detect version from \"$without_ext\"";;
+	esac
+
+	echo "$version" | sed 's/^v//'
 }
 
 
@@ -784,6 +942,8 @@ case $command in
 		cmd_cat "$@";;
 	create)
 		cmd_create "$@";;
+	debuild)
+		cmd_debuild "$@";;
 	edit)
 		cmd_edit "$@";;
 	fetch)
@@ -802,6 +962,8 @@ case $command in
 		cmd_outdated "$@";;
 	repotest)
 		cmd_repotest "$@";;
+	rpmbuild)
+		cmd_rpmbuild "$@";;
 	search)
 		cmd_search "$@";;
 	update)
